### ISSUE TITLE
API review

### ISSUE THREAD

**Issue by marcanpilami** [enioka/enioka_scan#44]
Too many verbs inside Scanner.
Are all Scanner subinterfaces needed?
Advanced commands: get out of jail API
No more sync
Rename namespaces

**Comment by DaSpood** [comment]
### CODE:

* supprimer GenericHidScanner (trop de compromis pour intéret limité)
* supprimer ScannerForeground (plus d'utilisation)
* supprimer ScannerBackground (inclure directement dans Scanner)
* ajouter un convertisseur intent<->options pour simplifier le traitement ?
* refactor l'architecture ?
	* package helper / api / service: réorganiser les classes, appartenance floue
	* doc manquante

### API SCANNERSERVICE:

* Fore/BackgroundScannerClient -> vraiment utiles après suppression de ScannerFore/Background ?
* revisiter les options de selection des scanners
	* whitelist par défaut ou blacklist par défaut ?
	* lister tous les providers d'abord pour permettre whitelist/blacklist au runtime ?
	* lister tous les scanners disponibles d'abord et proposer de filtrer selon options ensuite ?
* tri des méthodes présentées
	* `getFirstScannerStatus` ; `anyScannerSupports/HasIllumination`, `takeForegroundControl` -> vraiment toutes utiles ?
	* interface directe avec les scanners, juste "gestionnaire" de scanners ou entre-deux ? -> choix à faire
* manque de moyens de modifier le comportement du service/des scanners post-init

### LASER SCANNER:

* étendre la fonctionnalité de recherche de scanner ?
	* si fonctionnement par whitelist, pas besoin de "recherche", directement tenter d'instancier
	* déclinaisons de `getLaserScanner` (recherche générale, uniquement selon whitelist, uniquement un provider spécifique...) ?
	* `getProviders` en accès publique / au moins pour lister les providers disponibles ?
	=> Si l'application client cible un scanner particulier, pas besoin de tout le process de recherche, cible déjà connue
	=> Si l'application client n'a pas de cible précise, possible besoin d'une étape entre la recherche des providers et la création des scanners pour filtrer/paramétrer davantage

### API SCANNER:

* donner un accès direct au scanner / `getUnderlyingDevice` -> difficile a généraliser entre scanners bluetooth / intent / internes (camera)
* simplifier l'API: besoin de toutes les méthodes proposées ?
	* possibilité de séparer les méthodes en interfaces dédiées (hasLED, hasIllumination, hasBeep...) ?
			=> Utilisation un peu moins pratique (besoin de cast en fonction des interfaces disponibles) mais implémentation plus simple (moins de méthodes override "pour rien")
* améliorer paramétrage du scanner
	* actuellement: params par défaut propres à chaque SDK
	* difficulté: config propre à chaque SDK, difficile de proposer une interface commune
	* possibilités:
		* lister les symbologies disponibles et permettre la sélection
		* paramètres disponibles via interfaces du scanner (hasLED, hasIllumination... cf plus haut)
	* limitations:
		* manque d'intéret réel, besoin de config précise = trop spécifique, laisser l'utilisateur se débrouiller directement avec le scanner si nécéssaire
